package sbnz.integracija;

import sbnz.integracija.chefadvisor.facts.SearchInputFact
import sbnz.integracija.chefadvisor.facts.SearchResultFact
import sbnz.integracija.chefadvisor.domain.Dish
import sbnz.integracija.chefadvisor.domain.enumeration.DishCategory
import sbnz.integracija.chefadvisor.domain.Ingredient
import java.util.Set


rule "Find missing Ingredients"
	agenda-group "reverse-search"
	when
        $s: SearchInputFact( $fridge: fridge, $dishes: dishes )
        $srf: SearchResultFact()
        $d: Dish( $requiredIngredients: ingredients ) from $dishes
        $requiredIngredient: Ingredient() from $requiredIngredients
        not(exists ( Ingredient( ingredientModel.id == $requiredIngredient.ingredientModel.id) from $fridge))
    then
    	$srf.getMissingIngredients().add($requiredIngredient);
end

rule "Find ingredients with amount that is not enough"
	agenda-group "reverse-search"
	when
        $s: SearchInputFact( $fridge: fridge, $dishes: dishes )
        $srf: SearchResultFact()
        $d: Dish( $requiredIngredients: ingredients ) from $dishes
        $requiredIngredient: Ingredient() from $requiredIngredients
        $ingredientWithLowerAmount: Ingredient( ingredientModel.id == $requiredIngredient.ingredientModel.id && amount < $requiredIngredient.amount) from $fridge
    then
    	$requiredIngredient.setAmount($requiredIngredient.getAmount() - $ingredientWithLowerAmount.getAmount());
    	$srf.getMissingIngredients().add($requiredIngredient);
end

